#ifndef TUYA_CONFIG_H
#define TUYA_CONFIG_H

#define TUYA_PRODUCT_ID "YOUR_PRODUCT_ID"
#define TUYA_DEVICE_UUID "YOUR_DEVICE_UUID"
#define TUYA_DEVICE_AUTHKEY "YOUR_DEVICE_AUTHKEY"

#endif // TUYA_CONFIG_H
